# Generated by Django 5.2.6 on 2025-09-12 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текcт вопроса')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers_f', to=settings.AUTH_USER_MODEL)),
                ('questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers_f', to='questions_api.questions')),
            ],
            options={
                'ordering': ['date_create'],
            },
        ),
    ]
